name: CI Pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-test-lint-docker:
        runs-on: ubuntu-latest

        steps:
            # ----- Checkout code -----
            - name: Checkout repository
              uses: actions/checkout@v3

            # ----- Setup Python -----
            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            # ----- Install dependencies -----
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            # ----- Lint Code (black + isort) -----
            - name: Run Black
              run: black --check .

            - name: Run isort
              run: isort --check-only .

            # ----- Pylint -----
            - name: Run pylint
              run: pylint bsort --fail-under=6

            # ----- Unit Tests (pytest) -----
            - name: Run pytest
              run: pytest -q

            # # ----- Docker Build -----
            # - name: Build Docker image
            #   run: docker build -t bottlecap-detector .
